### ISSUE TITLE
NEI item search gets stuck on highlighted search mode

### ISSUE THREAD

**Issue by Haringat** [Chicken-Bones/NotEnoughItems#104]
OS: Linux
Minecraft: 1.7.10
Forge: 10.13.1.1219
CCC: 1.0.3.28
NEI: 1.0.3.60

Full log: http://pastebin.com/ftvgSbNy
exception(also in log):
Exception in thread "NEI Item Filtering" [23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.ConcurrentModificationException
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.util.LinkedList$ListItr.next(LinkedList.java:888)
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at mcp.mobius.waila.handlers.nei.ModNameFilter$Filter.matches(ModNameFilter.java:71)
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at codechicken.nei.ItemList.itemMatches(ItemList.java:76)
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at codechicken.nei.ItemList$2.execute(ItemList.java:173)
[23:35:10] [NEI Item Filtering/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24)

Reproducible: yes
Steps to reproduce:
1. open up inventory
2. double click on the search bar
3. type in anything

**Comment by participle38** [comment]
All other things being equal, I experienced this issue on 1.0.4.79 and 1.0.4.80 but not on 1.0.3.78.

**Comment by TBoshoven** [comment]
For me 1.7.10-1.0.3.77-universal seems to be fine. Maybe it's an incompatibility with another mod? My previous report was the DW20 FTB pack. This one is The Dark Trilogy (1.0.7).
