### ISSUE TITLE
crash on 1.8

### ISSUE THREAD

**Issue by yunlifang** [Chicken-Bones/NotEnoughItems#151]
the nestest NEI plugin crash on 1.8, logs:
[17:00:39] [Client thread/INFO] [STDOUT/NotEnoughItems]: [net.minecraft.init.Bootstrap:func_179870_a:492]: ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 15-1-14 下午5:00
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setBoolean(Ljava/lang/String;Z)V
	at codechicken.nei.ItemStackMap.<clinit>(ItemStackMap.java:206)
	at codechicken.nei.api.ItemInfo.<clinit>(ItemInfo.java:58)
	at codechicken.nei.ClientHandler.preInit(ClientHandler.java:100)
	at codechicken.nei.NEIModContainer.preInit(NEIModContainer.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:84)

**Comment by Chicken-Bones** [comment]
Full FML log required

**Comment by da3dsoul** [comment]
Don't even, you can tell it's merely using the deob version in normal minecraft.

**Comment by Chicken-Bones** [comment]
Huh? I asked for a full FML log because it shows me version numbers and filenames, as well as other mods.

**Comment by da3dsoul** [comment]
Oh, then yes. That would be a great reason.

**Comment by alexbegt** [comment]
This has been fixed with 1.0.5.96, I have updated the mappings that NEI, CodeChickenLib, and CodeChickenCore are running. Make sure to update them also.
