### ISSUE TITLE
Strange behaviour of hotbar slot 2 in crafting GUI

### ISSUE THREAD

**Issue by firx** [Chicken-Bones/NotEnoughItems#156]
On the crafting grid (testing using vanilla crafting table), with a recipe loaded with items and the mouse cursor over the output box, pressing a hotbar key (for which the corresponding hotbar slot is empty) will normally craft a single item and place it in the hotbar slot.

With NEI (tested using 1.7.10 and 1.8.1) the behaviour changes for hotbar slot 2 but all the others remain normal. The altered behaviour for slot 2 is that it crafts as many items as possible and leaves them "picked up" by the mouse.

I did a little debugging as well:

It still happens if the mouse buttons are rebound, or completely unbound.
It still happens only on slot 2 even if the hotbar keys are rebound to different keys.

I poked around the code a bit and maybe it's to do with this code from GuiContainer.java (from the 1.7 branch, but code is similar on master):

              if (p_146983_1_ == this.mc.gameSettings.keyBindsHotbar[j].getKeyCode())
                 {
                     managerHandleMouseClick(this.theSlot, this.theSlot.slotNumber, j, 2);
                     return true;
                 }
             }

It seems like managerHandleMouseClick's third parameter (here, j) is the mouse button that's clicking -- which would match the behaviour because mouse button 2 (which would happen when j == 2) would normally perform the action of crafting as many items as possible. Disclaimer: I'm no java programmer ;-)

**Comment by firx** [comment]
I've done some further debugging and when '2' is pressed on the keyboard, we end up in handleSlotClick() in NEIController.java, where it simulates 64 clicks (near line 130). This seems wrong because it's obviously mouse-related code but we're getting there on a keyboard event.

I got Java to throw an exception there, and found that the path leading there from a keyboard event is this:
Stacktrace:
	at codechicken.nei.NEIController.handleSlotClick(NEIController.java:132)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:672)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:649)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

Where as normally (for a mouse click) it's this:

Stacktrace:
	at codechicken.nei.NEIController.handleSlotClick(NEIController.java:132)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

So I tried removing this line that (maybe?) hooks up that sequence for only the keyboard, from NEITransformer.java (around line 117):

        transformer.add(new MethodReplacer(new ObfMapping(GuiContainer, "func_146983_a", "(I)Z"), asmblocks.get("d_handleMouseClick"), asmblocks.get("handleMouseClick")));//checkHotbarKeys

... and it fixes the problem for me. I don't understand how this part works, so I'm not claiming that this is an actual fix but maybe it'll help to create one :-) (It doesn't seem to have broken the hotbar keys tho.)

**Comment by firx** [comment]
I've done some further debugging and when '2' is pressed on the keyboard, we end up in handleSlotClick() in NEIController.java, where it simulates 64 clicks (near line 130). This seems wrong because it's obviously mouse-related code but we're getting there on a keyboard event.

I got Java to throw an exception there, and found that the path leading there from a keyboard event is this:
Stacktrace:
at codechicken.nei.NEIController.handleSlotClick(NEIController.java:132)
at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:672)
at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:649)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

Where as normally (for a mouse click) it's this:

Stacktrace:
at codechicken.nei.NEIController.handleSlotClick(NEIController.java:132)
at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

So I tried removing this line that (maybe?) hooks up that sequence for only the keyboard, from NEITransformer.java (around line 117):

    transformer.add(new MethodReplacer(new ObfMapping(GuiContainer, "func_146983_a", "(I)Z"), asmblocks.get("d_handleMouseClick"), asmblocks.get("handleMouseClick")));//checkHotbarKeys

... and it fixes the problem for me. I don't understand how this part works, so I'm not claiming that this is an actual fix but maybe it'll help to create one :-) (It doesn't seem to have broken the hotbar keys tho.)
