### ISSUE TITLE
Randomly Appears

### ISSUE THREAD

**Issue by O13SC3N3** [Chicken-Bones/NotEnoughItems#170]
Half the time during new World Generation, sometimes randomly during play. Sometimes Lags.

[22:30:28] [Client thread/ERROR] [NotEnoughItems]: Error loading brewing ingredients for: net.minecraft.item.ItemBlock@76b1f15d
java.lang.NullPointerException
	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:407) [ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) [ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[22:30:28] [Server thread/INFO] [FastCraft-core]: 19 / 19 applied
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: mods.railcraft.common.blocks.aesthetics.post.ItemPostMetal@65c12b40
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: mods.railcraft.common.blocks.aesthetics.post.ItemPostMetal@5de0508f
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: net.minecraft.item.ItemBlock@70d15e06
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: mods.natura.items.BerryMedley@f466be5
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: cofh.thermalfoundation.item.ItemLexicon@27ad3727
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: cofh.thermalexpansion.item.tool.ItemWrench@b6fb66d
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: cofh.thermalexpansion.item.tool.ItemIgniter@cbffdd5
[22:30:29] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: cofh.thermalexpansion.item.ItemFlorb@60e69446

**Comment by Robijnvogel** [comment]
#178 is similar

There are multiple people on the minecraft forums with the same problem:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?page=1076#c22089
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct?page=130#c2611
It kicks people from servers or doesn't let them enter a single player game.

I wonder what mod adds this "BlockFlower" brewing recipe anyway.
