### ISSUE TITLE
game stop responding when i go to the second page of NEI

### ISSUE THREAD

**Issue by jochuan** [Chicken-Bones/NotEnoughItems#171]
i am using the latest 1.7.10 NEI version and everytime i go to the second page the game stop responding here is the error on the log of the launcher: 

[09:11:14] [Client thread/ERROR] [FML]: Unable to determine registrant mod for codechicken.lib.render.TextureUtils@7cc70d. This is a critical error and should be impossible java.lang.Throwable at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?] at codechicken.lib.render.TextureUtils.<clinit>(TextureUtils.java:33) [TextureUtils.class:?] at codechicken.nei.SpawnerRenderer.renderInventoryItem(SpawnerRenderer.java:39) [SpawnerRenderer.class:?] at codechicken.nei.SpawnerRenderer.renderItem(SpawnerRenderer.java:81) [SpawnerRenderer.class:?] at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183) [ForgeHooksClient.class:?] at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) [bny.class:?] at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:187) [GuiContainerManager.class:?] at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:177) [GuiContainerManager.class:?] at codechicken.nei.ItemPanel.draw(ItemPanel.java:129) [ItemPanel.class:?] at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:196) [LayoutManager.class:?] at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:387) [GuiContainerManager.class:?] at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120) [bex.class:?] at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358) [blt.class:?] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989) [bao.class:?] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?] at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40] at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by Chicken-Bones** [comment]
Oh I uhh, fixed this I think, try the latest version
