### ISSUE TITLE
my world didn't open

### ISSUE THREAD

**Issue by jochuan** [Chicken-Bones/NotEnoughItems#178]
i am using the latest version for 1.7.10

[10:18:56] [Client thread/ERROR] [NotEnoughItems]: Error loading brewing ingredients for: net.minecraft.item.ItemBlock@b9696a
java.lang.NullPointerException
	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:412) [ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) [ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:18:56] [Client thread/ERROR] [NotEnoughItems]: Error loading brewing ingredients for: net.minecraft.item.ItemBlock@1c43565
java.lang.NullPointerException
	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:412) [ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) [ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:18:56] [Client thread/ERROR] [NotEnoughItems]: Error loading brewing ingredients for: net.minecraft.item.ItemBlock@b8b7c8
java.lang.NullPointerException
	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:412) [ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) [ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:18:56] [Client thread/ERROR] [NotEnoughItems]: Error loading brewing ingredients for: net.minecraft.item.ItemBlock@b3f968
java.lang.NullPointerException
	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:412) [ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) [ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by Chicken-Bones** [comment]
That's a non-crash error

**Comment by jochuan** [comment]
yes it make my game stop responding

**Comment by Chicken-Bones** [comment]
Send a full FML log?
