### ISSUE TITLE
NEI search not doing anything

### ISSUE THREAD

**Issue by Zaflis** [Chicken-Bones/NotEnoughItems#183]
I can see NEI (Options button and Prev, Next on top right corner). But it isn't searching anything, the right side is always 0 items no matter what i type in search field. I already tried deleting NEI.dat related to that world from client folders. It was still working with the 1.0.3.74 recommended version.

NotEnoughItems-1.7.10-1.0.4.95-universal
forge-1.7.10-10.13.2.1291-universal (latest recommended)
neiaddons-mc1710-1.12.5.17
NEIIntegration-MC1.7.10-1.0.7
INpureCore-[1.7.10]1.0.0B9-54

**Comment by Zaflis** [comment]
Found the culprit. Doubleclicking search bar caused a crash that gave report:

java.lang.AbstractMethodError: com.austinv11.thaumicnei.filters.AspectFilter.isPrimary()Z
	at codechicken.nei.SearchField.getFilter(SearchField.java:133)
	at codechicken.nei.ItemList.getItemFilters(ItemList.java:153) ...

So i went and disabled ThaumicNEI-1.7.10-0.1.2 from server and client, and everything is working.
