### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by PavelInt** [Chicken-Bones/NotEnoughItems#184]
When viewing recipes in IС2 in the console there is an error.

**Comment by O13SC3N3** [comment]
Can confirm with builds ic2 708 to 714

[13/4/2015 22:15:46 PM] [Client thread/WARN] [IC2.Item]: Detected invalid armor damage application:
[13/4/2015 22:15:46 PM] java.lang.Throwable
[13/4/2015 22:15:46 PM] 	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:149) [ItemArmorElectric.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) [add.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.PositionedStack.setPermutationToRender(PositionedStack.java:99) [PositionedStack.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:34) [PositionedStack.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.setIngredients(ShapedRecipeHandler.java:53) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
[13/4/2015 22:15:46 PM] 	at ic2.neiIntegration.core.AdvRecipeHandler.createCachedRecipe(AdvRecipeHandler.java:35) [AdvRecipeHandler.class:?]
[13/4/2015 22:15:46 PM] 	at ic2.neiIntegration.core.AdvRecipeHandler.loadUsageRecipes(AdvRecipeHandler.java:68) [AdvRecipeHandler.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346) [TemplateRecipeHandler.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471) [TemplateRecipeHandler.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:39) [RecipeItemInputHandler.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329) [GuiContainerManager.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java) [bex.class:?]
[13/4/2015 22:15:46 PM] 	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102) [GuiRecipe.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) [bex.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628) [bao.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[13/4/2015 22:15:46 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
[13/4/2015 22:15:46 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[13/4/2015 22:15:46 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[13/4/2015 22:15:46 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
[13/4/2015 22:15:46 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[13/4/2015 22:15:46 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
