### ISSUE TITLE
Error handling SMP Check -> NEI not showing up on client.  

### ISSUE THREAD

**Issue by lehjr** [Chicken-Bones/NotEnoughItems#190]
I upgraded forge (currenty to 1.7.10-10.13.3.1381) and NEI no longer shows up, but shows up in the "mod list" as "Mod State: Available".
relevant versions:	
industrialcraft-2-2.2.717-experimental.jar
CodeChickenLib-1.7.10-1.1.3.134-universal.jar
CodeChickenCore-1.7.10-1.0.5.37-universal.jar
NotEnoughItems-1.7.10-1.0.4.95-universal.jar

Unfortunately downgrading forge isn't really an option as more mods are requiring newer versions. 

The log doesn't show anything unusual except this:

[21:42:54] [Client thread/ERROR] [NotEnoughItems/]: Error handling SMP Check
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23) ~[dx.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105) ~[dh.class:?]
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:96) ~[FluidStack.class:?]
	at ic2.core.item.ItemIC2FluidContainer.fill(ItemIC2FluidContainer.java:92) ~[ItemIC2FluidContainer.class:?]
	at ic2.core.item.ItemFluidCell.func_150895_a(ItemFluidCell.java:116) ~[ItemFluidCell.class:?]
	at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:368) ~[ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.load(ItemInfo.java:96) ~[ItemInfo.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) ~[NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) ~[NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by lehjr** [comment]
To add to this.. it does work again in later versions. And while it is nice to have the mod itself crash while leaving the game still playable, maybe it would be better to ignore invalid fluids through a "try-catch" or some other means.

**Comment by Chicken-Bones** [comment]
While this was an IC2 issue, I do agree, it's NEI's job to catch this and just ignore the item, rather than kill NEI completely. So...
Fixed e99febf27ce3bf5588881c20bbcd29067a926545 (1.7.10-1.0.4.99)
