### ISSUE TITLE
[1.7.10] Client process death due to NPE: Rendering screen (minimal reproducible test case)

### ISSUE THREAD

**Issue by politician** [Chicken-Bones/NotEnoughItems#247]
People have been running into a crash-to-desktop NPE when running SMP with reports dating back to 2013.  I've managed to put together a _minimal_ reproducible "modpack" and corresponding server which implicates NEI, not other mods, as the culprit.   Find a proposed fix and the logs below, hopefully this helps track this down.  Not sure why the Slot is null, must be a mistaken assumption higher up the call stack; hopefully, just checking for null resolves the issue.

##### Client Versions
```
Minecraft:  1.7.10
Forge: 10.13.4.1448
CodeChickenCore: 1.0.7.46
NotEnoughItems: 1.0.5.111  
```

##### Server Versions
```
Minecraft:  1.7.10
Forge: 10.13.4.1448
CodeChickenCore: 1.0.7.46
NotEnoughItems: 1.0.5.111  
```

### Affected Call-site

https://github.com/Chicken-Bones/NotEnoughItems/blob/master/src/codechicken/nei/LayoutManager.java#L719

```Java
    @Override
    public void renderSlotOverlay(GuiContainer window, Slot slot) {
        ItemStack item = slot.getStack();  // NPE in SMP -- slot is null!
        if (world.nbt.getBoolean("searchinventories") && (item == null ? !getSearchExpression().equals("") : !ItemList.itemMatches(item))) {
            GlStateManager.disableLighting();
            GlStateManager.translate(0, 0, 150);
            drawRect(slot.xDisplayPosition, slot.yDisplayPosition, 16, 16, 0x80000000);
            GlStateManager.translate(0, 0, -150);
            GlStateManager.enableLighting();
        }
    }
```

#### Proposed Fix

Since renderSlotOverlay does nothing if `item` is null, I think it's reasonable to just return if the `slot` itself is null.

```Java
 @Override
    public void renderSlotOverlay(GuiContainer window, Slot slot) {
        if (slot == null) return;
        ItemStack item = slot.getStack();  // NPE in SMP -- slot is null!
```

### Crash Logs

```
[11:14:35] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/26/15 11:14 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at codechicken.nei.LayoutManager.renderSlotOverlay(LayoutManager.java:719)
	at codechicken.nei.guihook.GuiContainerManager.renderSlotOverlay(GuiContainerManager.java:432)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.nei.LayoutManager.renderSlotOverlay(LayoutManager.java:719)
	at codechicken.nei.guihook.GuiContainerManager.renderSlotOverlay(GuiContainerManager.java:432)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (170, 75). Absolute: (341, 329)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['xxxxxxx'/2633, l='MpServer', x=46.50, y=71.62, z=259.50]]
	Chunk stats: MultiplayerChunkCache: 340, 340
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (52,64,256), Chunk: (at 4,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1746 game time, 1746 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 120 total; [EntitySpider['Spider'/3840, l='MpServer', x=58.71, y=17.00, z=272.74], EntityClientPlayerMP['cracklekazoo'/2633, l='MpServer', x=46.50, y=71.62, z=259.50], EntityBat['Bat'/3077, l='MpServer', x=55.52, y=56.14, z=284.02], EntityZombie['Zombie'/2824, l='MpServer', x=39.50, y=18.00, z=315.50], EntitySkeleton['Skeleton'/3852, l='MpServer', x=115.50, y=49.00, z=282.50], EntitySkeleton['Skeleton'/3853, l='MpServer', x=116.50, y=49.00, z=283.50], EntitySpider['Spider'/3600, l='MpServer', x=-17.01, y=36.61, z=289.28], EntityCreeper['Creeper'/3604, l='MpServer', x=119.50, y=15.00, z=236.50], EntitySkeleton['Skeleton'/3605, l='MpServer', x=125.50, y=15.00, z=230.50], EntityZombie['Zombie'/3606, l='MpServer', x=47.50, y=18.00, z=314.50], EntityZombie['Zombie'/3368, l='MpServer', x=117.50, y=15.00, z=236.50], EntityZombie['Zombie'/3370, l='MpServer', x=4.50, y=23.00, z=222.50], EntityZombie['Zombie'/3371, l='MpServer', x=5.50, y=23.00, z=219.50], EntityZombie['Zombie'/3631, l='MpServer', x=95.50, y=18.00, z=180.50], EntitySheep['Sheep'/55, l='MpServer', x=-25.50, y=90.00, z=190.28], EntitySheep['Sheep'/56, l='MpServer', x=-29.50, y=90.00, z=195.50], EntitySheep['Sheep'/57, l='MpServer', x=-30.50, y=90.00, z=197.50], EntitySheep['Sheep'/58, l='MpServer', x=-32.50, y=89.00, z=193.50], EntitySheep['Sheep'/59, l='MpServer', x=-32.19, y=67.00, z=254.28], EntityBat['Bat'/3132, l='MpServer', x=78.62, y=22.00, z=295.25], EntitySheep['Sheep'/60, l='MpServer', x=-28.94, y=67.00, z=254.25], EntitySheep['Sheep'/61, l='MpServer', x=-28.47, y=67.00, z=257.78], EntityBat['Bat'/3139, l='MpServer', x=69.75, y=15.00, z=260.25], EntitySkeleton['Skeleton'/3142, l='MpServer', x=10.50, y=22.00, z=276.50], EntityCreeper['Creeper'/3143, l='MpServer', x=7.50, y=22.00, z=276.50], EntitySpider['Spider'/3658, l='MpServer', x=72.20, y=28.32, z=318.81], EntityEnderman['Enderman'/3661, l='MpServer', x=74.25, y=29.00, z=318.34], EntityEnderman['Enderman'/3662, l='MpServer', x=70.50, y=28.00, z=315.50], EntitySheep['Sheep'/79, l='MpServer', x=-11.50, y=81.00, z=196.50], EntitySheep['Sheep'/80, l='MpServer', x=-14.53, y=81.00, z=205.47], EntitySheep['Sheep'/81, l='MpServer', x=-11.56, y=81.00, z=199.69], EntitySheep['Sheep'/82, l='MpServer', x=-12.53, y=81.00, z=198.47], EntitySheep['Sheep'/83, l='MpServer', x=-14.34, y=74.00, z=219.50], EntitySheep['Sheep'/84, l='MpServer', x=-19.94, y=71.00, z=221.47], EntitySkeleton['Skeleton'/3156, l='MpServer', x=113.50, y=16.00, z=219.50], EntitySheep['Sheep'/85, l='MpServer', x=-20.50, y=70.00, z=224.50], EntitySheep['Sheep'/86, l='MpServer', x=-22.50, y=69.00, z=227.50], EntityCow['Cow'/87, l='MpServer', x=-18.50, y=68.00, z=294.50], EntityCow['Cow'/88, l='MpServer', x=-22.50, y=68.00, z=295.50], EntityCow['Cow'/89, l='MpServer', x=-20.50, y=68.00, z=294.50], EntityCow['Cow'/90, l='MpServer', x=-15.50, y=66.00, z=290.50], EntitySheep['Sheep'/91, l='MpServer', x=-12.78, y=83.00, z=319.28], EntitySheep['Sheep'/92, l='MpServer', x=-13.38, y=76.00, z=316.28], EntitySheep['Sheep'/93, l='MpServer', x=-10.28, y=78.00, z=318.53], EntitySheep['Sheep'/94, l='MpServer', x=-12.50, y=79.00, z=320.50], EntityCreeper['Creeper'/3422, l='MpServer', x=103.50, y=36.00, z=280.50], EntityChicken['Chicken'/95, l='MpServer', x=-24.47, y=77.00, z=324.53], EntityChicken['Chicken'/96, l='MpServer', x=-26.47, y=66.00, z=313.47], EntityChicken['Chicken'/97, l='MpServer', x=-22.66, y=72.00, z=322.56], EntityChicken['Chicken'/98, l='MpServer', x=-24.53, y=75.00, z=315.53], EntityZombie['Zombie'/3691, l='MpServer', x=55.55, y=23.70, z=325.00], EntityCreeper['Creeper'/2668, l='MpServer', x=113.50, y=26.00, z=255.50], EntitySpider['Spider'/3692, l='MpServer', x=59.02, y=24.00, z=324.54], EntitySheep['Sheep'/112, l='MpServer', x=19.50, y=68.00, z=204.50], EntitySheep['Sheep'/113, l='MpServer', x=19.50, y=68.00, z=202.72], EntitySheep['Sheep'/114, l='MpServer', x=19.50, y=68.00, z=206.28], EntitySheep['Sheep'/115, l='MpServer', x=19.50, y=68.00, z=204.50], EntitySheep['Sheep'/116, l='MpServer', x=12.78, y=70.00, z=283.50], EntitySheep['Sheep'/117, l='MpServer', x=21.25, y=75.00, z=289.53], EntitySheep['Sheep'/118, l='MpServer', x=9.50, y=69.00, z=282.50], EntitySheep['Sheep'/119, l='MpServer', x=14.38, y=70.00, z=282.81], EntitySheep['Sheep'/120, l='MpServer', x=14.50, y=70.00, z=305.50], EntitySheep['Sheep'/121, l='MpServer', x=14.50, y=70.00, z=308.50], EntitySkeleton['Skeleton'/3705, l='MpServer', x=93.38, y=29.00, z=326.13], EntitySheep['Sheep'/122, l='MpServer', x=16.47, y=70.00, z=308.53], EntitySheep['Sheep'/123, l='MpServer', x=17.53, y=70.00, z=307.47], EntitySkeleton['Skeleton'/3198, l='MpServer', x=120.50, y=36.00, z=273.50], EntityZombie['Zombie'/3199, l='MpServer', x=111.22, y=35.00, z=277.50], EntitySheep['Sheep'/132, l='MpServer', x=34.94, y=70.00, z=277.55], EntitySpider['Spider'/2948, l='MpServer', x=68.81, y=30.00, z=290.06], EntitySheep['Sheep'/133, l='MpServer', x=34.40, y=69.00, z=276.21], EntitySpider['Spider'/2949, l='MpServer', x=67.81, y=31.00, z=292.56], EntitySkeleton['Skeleton'/2693, l='MpServer', x=48.76, y=20.00, z=307.77], EntitySkeleton['Skeleton'/3461, l='MpServer', x=39.50, y=18.00, z=267.50], EntitySheep['Sheep'/134, l='MpServer', x=34.47, y=70.00, z=279.38], EntitySkeleton['Skeleton'/2694, l='MpServer', x=49.69, y=20.00, z=308.48], EntitySkeleton['Skeleton'/3462, l='MpServer', x=40.50, y=18.00, z=267.50], EntitySheep['Sheep'/135, l='MpServer', x=31.50, y=69.00, z=278.50], EntitySkeleton['Skeleton'/2695, l='MpServer', x=51.50, y=21.00, z=302.50], EntitySkeleton['Skeleton'/2696, l='MpServer', x=51.56, y=25.00, z=296.20], EntityCreeper['Creeper'/2958, l='MpServer', x=116.50, y=49.00, z=284.50], EntityCreeper['Creeper'/3726, l='MpServer', x=76.50, y=24.00, z=206.50], EntityCreeper['Creeper'/2959, l='MpServer', x=117.50, y=49.00, z=282.50], EntityCreeper['Creeper'/2960, l='MpServer', x=116.50, y=49.00, z=281.50], EntitySheep['Sheep'/148, l='MpServer', x=71.50, y=66.00, z=284.50], EntitySheep['Sheep'/149, l='MpServer', x=71.50, y=65.00, z=287.50], EntitySheep['Sheep'/150, l='MpServer', x=69.78, y=66.00, z=284.50], EntitySheep['Sheep'/151, l='MpServer', x=68.19, y=67.00, z=284.50], EntityBat['Bat'/3224, l='MpServer', x=49.33, y=25.50, z=274.91], EntityBat['Bat'/3225, l='MpServer', x=44.34, y=25.13, z=290.35], EntityBat['Bat'/3226, l='MpServer', x=44.23, y=25.83, z=286.37], EntitySheep['Sheep'/164, l='MpServer', x=100.41, y=76.00, z=277.66], EntitySheep['Sheep'/165, l='MpServer', x=96.50, y=74.00, z=275.50], EntitySheep['Sheep'/166, l='MpServer', x=99.22, y=74.00, z=276.06], EntitySheep['Sheep'/167, l='MpServer', x=101.53, y=74.00, z=277.53], EntitySheep['Sheep'/168, l='MpServer', x=96.50, y=67.00, z=306.50], EntitySheep['Sheep'/169, l='MpServer', x=96.72, y=65.00, z=305.53], EntitySheep['Sheep'/170, l='MpServer', x=91.94, y=68.00, z=309.53], EntityZombie['Zombie'/3242, l='MpServer', x=72.47, y=20.00, z=274.54], EntitySheep['Sheep'/171, l='MpServer', x=95.50, y=70.00, z=308.50], EntitySheep['Sheep'/172, l='MpServer', x=95.50, y=74.00, z=325.50], EntitySheep['Sheep'/173, l='MpServer', x=95.50, y=74.00, z=321.50], EntitySheep['Sheep'/174, l='MpServer', x=97.50, y=72.00, z=318.50], EntitySheep['Sheep'/175, l='MpServer', x=97.50, y=72.00, z=318.50], EntityBat['Bat'/3248, l='MpServer', x=54.57, y=24.00, z=204.47], EntityBat['Bat'/3249, l='MpServer', x=50.77, y=27.33, z=209.31], EntitySkeleton['Skeleton'/3271, l='MpServer', x=109.50, y=28.00, z=262.50], EntityZombie['Zombie'/3273, l='MpServer', x=80.50, y=42.00, z=288.50], EntityBat['Bat'/3025, l='MpServer', x=-25.43, y=29.97, z=241.23], EntityBat['Bat'/3026, l='MpServer', x=-25.41, y=28.47, z=240.60], EntityBat['Bat'/3027, l='MpServer', x=-27.24, y=30.11, z=242.56], EntitySkeleton['Skeleton'/3550, l='MpServer', x=53.50, y=29.00, z=204.50], EntityCreeper['Creeper'/3303, l='MpServer', x=113.50, y=28.00, z=262.50], EntityWitch['Witch'/3305, l='MpServer', x=114.50, y=28.00, z=261.50], EntityCreeper['Creeper'/3306, l='MpServer', x=112.50, y=28.00, z=263.50], EntityZombie['Zombie'/2797, l='MpServer', x=62.50, y=18.00, z=290.50], EntityZombie['Zombie'/2798, l='MpServer', x=66.50, y=18.00, z=292.50], EntityCreeper['Creeper'/2799, l='MpServer', x=60.50, y=18.00, z=288.50], EntityCreeper['Creeper'/2800, l='MpServer', x=28.31, y=53.00, z=291.53], EntitySpider['Spider'/3839, l='MpServer', x=61.95, y=18.13, z=268.72]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 272610608 bytes (259 MB) / 568852480 bytes (542 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xmx1024m -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar) 
	UCHIJA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.6.20' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.6.20, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[11:14:35] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/xxxxxxx/Library/Application Support/technic/modpacks/xxxxxxx/crash-reports/crash-2015-07-26_11.14.35-client.txt
```

**Comment by politician** [comment]
Related: https://github.com/Chicken-Bones/NotEnoughItems/issues/235

**Comment by politician** [comment]
Alright, I've instrumented my fork of NEI, and determined that the `world` is null.  Unfortunately, there are lots and lots of `world` accesses throughout NEI; `renderSlotOverlay` just happens to be the first.  So what we're most likely looking at is a failure to handle our obligations related to when `world` is allocated in the SMP workflow.

It could be that `world` is completely invalid in an SMP scenario.  I don't know.

#### Instrumented Crash Log

```
[17:31:35] [Client thread/ERROR] [NotEnoughItems/]: Error handling SMP Check
java.lang.RuntimeException: java.io.IOException: No such file or directory
	at codechicken.lib.config.ConfigFile.load(ConfigFile.java:26) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.lib.config.ConfigFile.<init>(ConfigFile.java:14) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:215) ~[NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_45]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_45]
	at codechicken.lib.config.ConfigFile.load(ConfigFile.java:24) ~[CodeChickenLib-1.7.10-1.1.3.138-universal.jar:?]
	... 25 more
[17:31:35] [Client thread/DEBUG] [CCL ASM/]: Replacing method [agq.h()Lsa;] @ 9 - 10
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:39] [Client thread/ERROR] [NotEnoughItems/]: renderSlotOverlay: `world` is null
[17:31:40] [Client thread/DEBUG] [FML/]: Reverting to frozen data state.
[17:31:40] [Client thread/INFO] [FML/]: Applying holder lookups
[17:31:40] [Client thread/INFO] [FML/]: Holder lookups applied
```

**Comment by politician** [comment]
Ok, so looks like those errors are related, and that the problem is that the code is looking for `NEI.cfg` and when it doesn't find it it swallows an exception leaving a global variable `world` set to null, and doesn't log anything helpful.  Later, in `renderSlotOverlay` the NPE shows up.

https://github.com/politician/NotEnoughItems/blob/e15182b7c3447993aeb8b59deb8eb976d84c3abb/src/codechicken/nei/NEIClientConfig.java#L215

**Comment by politician** [comment]
So, the file path that it's looking for is _crazy sauce_.

`/Users/politician/Library/Application Support/technic/modpacks/mypack/saves/NEI/remote/192.168.59.103~25565/../../var/lib/minecraft/world/NEI.cfg`

Let's break that down:

Path | Explanation
--- | --- 
`/Users/politician/Library/Application Support/technic/modpacks/mypack/` | Technic modpack base dir
`saves/NEI/remote/192.168.59.103~25565/` | server path
`../../var/lib/minecraft/world/NEI.cfg` | *crazy* This is segment contains a location from the server. Is this right??

**Comment by politician** [comment]
It looks like NEI is placing too much trust in the server's world name.  It's taking the world name sent from the server, and then attempts to convert it into a file path without doing any validation or normalization.  My server sends the world name as `../../var/lib/minecraft/world` for some silly reason - but it's just a name, not a path!

This is somewhat equivalent to SQL injection.  For now, I'm going to remove the dependency on the server's world name since it's just used for this one purpose and the path already has a HOST:PORT number in it which should uniquely identify the world anyway.

**Comment by politician** [comment]
Yup, that worked; I've submitted a PR.

**Comment by Chicken-Bones** [comment]
We'll move all discussion to the PR.
