### ISSUE TITLE
Trouble building jar

### ISSUE THREAD

**Issue by politician** [Chicken-Bones/NotEnoughItems#248]
So, I'm trying to solve the issue I reported earlier (#247), but after downloading the source and building a jar successfully, the game crashes on startup with a missing method exception.  Can you please document the steps necessary to build this library, or upload your build script?

Here's the Dockerfile that I'm using to build -- it downloads the toolchain and builds the jar file and sticks it into a place where I can extract it.  Note the use of OpenJDK 1.7.  Should I be using Oracle Java 7 JDK?  I tried Java 8 - that failed right away.

```
FROM java:7-jdk
MAINTAINER politician <foo@bar.com>

# grab build dependencies
RUN  apt-get update \
 &&  apt-get install -y curl git

# checkout politician/NotEnoughItems
RUN  mkdir -p /var/lib/minecraft/mods \
 &&  mkdir -p /tmp/mod \
 &&  cd /tmp/mod \
 &&  git clone https://github.com/politician/NotEnoughItems.git . \
 &&  git checkout 1.7 \
 &&  chmod +x build/gradlew

# initialize Gradle - this will take a while because (insert rant)
RUN  cd /tmp/mod/build \
 &&  mkdir build | true \
 &&  ln -s /var/lib/minecraft/mods build/libs \
 &&  ./gradlew

COPY root/ /

VOLUME ["/var/lib/minecraft/mods"]

ENTRYPOINT ["/bin/bash"]

# this command just calls "gradlew jar"
CMD ["/usr/local/bin/build_jar"]
```

#### Crash Log

```
[15:39:00] [Client thread/INFO] [STDOUT/NotEnoughItems]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 7/26/15 3:39 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setBoolean(Ljava/lang/String;Z)V
	at codechicken.nei.ItemStackMap.<clinit>(ItemStackMap.java:206)
	at codechicken.nei.api.ItemInfo.<clinit>(ItemInfo.java:55)
	at codechicken.nei.ClientHandler.preInit(ClientHandler.java:113)
	at codechicken.nei.NEIModContainer.preInit(NEIModContainer.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.nei.ItemStackMap.<clinit>(ItemStackMap.java:206)
	at codechicken.nei.api.ItemInfo.<clinit>(ItemInfo.java:55)
	at codechicken.nei.ClientHandler.preInit(ClientHandler.java:113)
	at codechicken.nei.NEIModContainer.preInit(NEIModContainer.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 212829712 bytes (202 MB) / 418906112 bytes (399 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xmx1024m -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCH	Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar) 
	UCH	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.null} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.null-universal.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.6.20' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.6.20, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by politician** [comment]
[This thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2137859-1-7-10-not-enough-items-crash-problem) leads me to believe that I've built the jar in development mode.  If that's actually the problem, and anyone knows how to build it in "production" mode, I'd be grateful if you'd say something.  Otherwise, I'm going to go try to see if there's an option I've missed.

**Comment by politician** [comment]
Well, ok, I think I've fixed this.  I'm now calling `.gradlew SetupCIWorkspace` then `.gradlew build`.  That produces 3 jars, and the "universal" one seems to be the one that works.

**Comment by Chicken-Bones** [comment]
strange, it appears to be an obfuscation bug
