### ISSUE TITLE
Updating Screen Events Problem (All Version)

### ISSUE THREAD

**Issue by alvinandrius** [Chicken-Bones/NotEnoughItems#254]
I tried to open minecraft but the play button is becomne play offline button.Here is the crash problem.---- Minecraft Crash Report ----
// Ouch. That hurt

Time: 01/08/15 11:33
Description: Updating screen events

java.lang.IllegalStateException: failed to create a child event loop
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
at ll$1.a(SourceFile:44)
at ll$1.b(SourceFile:41)
at no.c(SourceFile:10)
at ll.a(SourceFile:121)
at ave.a(SourceFile:1941)
at axv.i(SourceFile:172)
at axv.a(SourceFile:135)
at axu.a(SourceFile:350)
at axu.k(SourceFile:413)
at axv.k(SourceFile:81)
at axu.p(SourceFile:390)
at ave.s(SourceFile:1497)
at ave.av(SourceFile:888)
at ave.a(SourceFile:325)
at net.minecraft.client.main.Main.main(SourceFile:124)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
... 18 more
Caused by: java.io.IOException: Unable to establish loopback connection
at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:101)
at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:68)
at java.security.AccessController.doPrivileged(Native Method)
at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:170)
at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
at java.nio.channels.Pipe.open(Pipe.java:155)
at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127)
at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
... 21 more
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 87: socket
at sun.nio.ch.Net.socket0(Native Method)
at sun.nio.ch.Net.serverSocket(Net.java:419)
at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:123)
at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:83)
... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

– Head –
Stacktrace:
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
at ll$1.a(SourceFile:44)
at ll$1.b(SourceFile:41)
at no.c(SourceFile:10)
at ll.a(SourceFile:121)
at ave.a(SourceFile:1941)
at axv.i(SourceFile:172)
at axv.a(SourceFile:135)
at axu.a(SourceFile:350)
at axu.k(SourceFile:413)
at axv.k(SourceFile:81)
at axu.p(SourceFile:390)

– Affected screen –
Details:
Screen name: aya
Stacktrace:
at ave.s(SourceFile:1497)
at ave.av(SourceFile:888)
at ave.a(SourceFile:325)
at net.minecraft.client.main.Main.main(SourceFile:124)

– System Details –
Details:
Minecraft Version: 1.8.7
Operating System: Windows 7 (amd64) version 6.1
CPU: 4x Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 75783024 bytes (72 MB) / 237502464 bytes (226 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: 1.8.7
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics GL version 3.3.0 - Build 8.15.10.2598, Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
And 1 more thing.I tried to log in and log out,but im stuck becuase when im logging in it makes this problem all the time every time i tried to log in.
SocketException:Unrecognize Windows Sockets error: 87: create
And i deleted my minecraft folder so probably i dont know how to complete this problem
And since my brother try to crack a paid game,it makes virus and my dad downloaded an Anti Virus for it.I tried to find a way.I tried to uninstall and reinstall.I tried to check the quarantine in anti virus and i already freed it.But it failed.I tried to update java,but it failed.

**Comment by alvinandrius** [comment]
One more thing.This is vanilla minecraft that i try to open!

**Comment by catzs** [comment]
Then why are you reporting this on the MOD-NEI's github?
