### ISSUE TITLE
Hammering Sound when open Nei 111 together with Extra Utilities 1.2.6-1.2.10

### ISSUE THREAD

**Issue by Dream-Master** [Chicken-Bones/NotEnoughItems#256]
I using Gregtech 5.08.26 and Extra utilities 1.2.6-1.2.10 and Nei Version 111 together and get some wired hammer sound (Minecraft Avil maybe IC2 Drill sounds) everytime when i open and close nei   From Time to time i get this Crash.

``````````````````````````````````
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 7/19/15 4:18 PM
Description: Unexpected error

java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:212)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

````````````````````````````````````

https://github.com/rwtema/extrautilities/issues/687

**Comment by Dream-Master** [comment]
And in Version 1.2.11

**Comment by mezz** [comment]
This should be fixed with this issue: https://github.com/Blood-Asp/GT5-Unofficial/issues/194

**Comment by Dream-Master** [comment]
Using forestry 3.6.10.1, gt 5.08.30 and extra utilities 1.2.11 and the hammering sound not gone. We have made a source pack for mc which muting the sound but this Is only a duct tape solution.

**Comment by atomicpulsz** [comment]
Can you link the resource pack? I haven't found a fix for this obnoxious anvil noise yet.

**Comment by Dream-Master** [comment]
send me an email i send you the link dream-master@gmx.net

**Comment by mezz** [comment]
I fixed a similar issue with GregTech tools in the Forestry Worktable or AE crafting window. Forestry and AE were calling `hasContainer` which also made a noise, I made a PR to GregTech so it doesn't make sound on that one.

I assume the problem has to do with NEI showing some ExU item that calls a GregTech tool's `getContainer` which makes a noise. It should only be called when the tool is being used, `hasContainer` should work for other purposes.

**Comment by Gregorius-MC** [comment]
It is worse with those people, who do things like enabling Sound Multithreading in the GT Config and then wonder about the constant crashes they get since it only works in SSP and also only on certain Computers without causing ConcurrentModificationExceptions.
Try this solution: open GregTech.cfg, them setup  "B:sound_multi_threading" option to false. Maybe it fix this problem)
p.s. http://forum.industrial-craft.net/index.php?page=Thread&postID=173754   (post 42,796)
