### ISSUE TITLE
[1.7.10] Crash when opening recipe for Ender Chest (FluidCannerRecipeHandler)

### ISSUE THREAD

**Issue by Kjasi** [Chicken-Bones/NotEnoughItems#296]
When opening the recipe for an Ender Chest, I always crash to the desktop. Log seems to indicate a problem with FluidCannerRecipeHandler.java.

I can create Ender Chests, use them, pretty much anything but look at their recipe in NEI. This issue doesn't seem to affect Ender Tanks or Ender Pouches at all. Only Ender Chests.

I am using the latest EnderStorage, ChickenCore and NEI versions that are listed here: http://chickenbones.net/Pages/links.html

Crash Log:

    ---- Minecraft Crash Report ----
    // Who set us up the TNT?
    
    Time: 11/9/15 4:39 PM
    Description: Updating screen events
    
    java.lang.NullPointerException: Updating screen events
        at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:140)
    	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    	at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:131)
    	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    	at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:80)
    	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- Head --
    Stacktrace:
    	at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:140)
    	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    	at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:131)
    	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    	at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:80)
    	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    
    -- Affected screen --
    Details:
    	Screen name: codechicken.nei.recipe.GuiCraftingRecipe
    
    -- Affected level --
    Details:
    	Level name: MpServer
    	All players: 1 total; [EntityClientPlayerMP['Kjasi'/349, l='MpServer', x=-195.97, y=5.62, z=312.91]]
    	Chunk stats: MultiplayerChunkCache: 441, 441
    	Level seed: 0
    	Level generator: ID 01 - flat, ver 0. Features enabled: false
    	Level generator options: 
    	Level spawn location: World: (-199,4,331), Chunk: (at 9,0,11 in -13,20; contains blocks -208,0,320 to -193,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    	Level time: 78184 game time, 135501 day time
    	Level dimension: 0
    	Level storage version: 0x00000 - Unknown?
    	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    	Forced entities: 144 total; [EntityPig['Pig'/257, l='MpServer', x=-143.94, y=4.00, z=392.06], EntityCow['Cow'/266, l='MpServer', x=-116.88, y=4.00, z=239.94], EntityPig['Pig'/268, l='MpServer', x=-121.75, y=4.00, z=257.88], EntityChicken['Chicken'/271, l='MpServer', x=-118.41, y=4.00, z=275.56], EntityHorse['Horse'/273, l='MpServer', x=-120.28, y=4.00, z=370.84], EntityCow['Cow'/274, l='MpServer', x=-120.97, y=4.00, z=391.88], EntityHorse['Horse'/277, l='MpServer', x=-127.34, y=4.00, z=391.72], EntityCow['Cow'/28, l='MpServer', x=-275.81, y=4.00, z=286.63], EntityHorse['Horse'/32, l='MpServer', x=-273.91, y=4.00, z=276.16], EntityHorse['Horse'/35, l='MpServer', x=-273.53, y=4.00, z=298.84], EntityChicken['Chicken'/36, l='MpServer', x=-274.63, y=4.00, z=297.47], EntityPig['Pig'/49, l='MpServer', x=-257.50, y=4.00, z=236.16], EntityCow['Cow'/50, l='MpServer', x=-259.78, y=4.00, z=247.19], EntityChicken['Chicken'/51, l='MpServer', x=-261.56, y=4.00, z=278.63], EntityChicken['Chicken'/52, l='MpServer', x=-267.41, y=4.00, z=291.94], EntityCreeper['Creeper'/54, l='MpServer', x=-265.03, y=4.00, z=302.50], EntityZombie['Zombie'/55, l='MpServer', x=-256.47, y=4.00, z=300.06], EntitySpider['Spider'/57, l='MpServer', x=-265.38, y=4.00, z=327.41], EntitySpider['Spider'/58, l='MpServer', x=-266.00, y=4.00, z=321.28], EntityChicken['Chicken'/59, l='MpServer', x=-256.53, y=4.00, z=341.47], EntitySheep['Sheep'/61, l='MpServer', x=-263.78, y=4.00, z=354.38], EntityChicken['Chicken'/62, l='MpServer', x=-259.53, y=4.00, z=352.44], EntityPig['Pig'/84, l='MpServer', x=-252.84, y=4.00, z=238.22], EntityPig['Pig'/85, l='MpServer', x=-244.88, y=4.00, z=234.44], EntityPig['Pig'/86, l='MpServer', x=-247.34, y=4.00, z=239.19], EntityCow['Cow'/87, l='MpServer', x=-245.94, y=4.00, z=238.41], EntitySheep['Sheep'/88, l='MpServer', x=-251.34, y=4.00, z=239.06], EntitySheep['Sheep'/89, l='MpServer', x=-245.13, y=4.00, z=239.50], EntitySheep['Sheep'/90, l='MpServer', x=-242.13, y=4.00, z=240.81], EntitySheep['Sheep'/91, l='MpServer', x=-252.53, y=4.00, z=240.47], EntityCow['Cow'/92, l='MpServer', x=-240.75, y=4.00, z=242.41], EntitySlime['Slime'/93, l='MpServer', x=-269.97, y=4.00, z=265.91], EntitySpider['Spider'/94, l='MpServer', x=-253.72, y=4.00, z=294.34], EntityChicken['Chicken'/95, l='MpServer', x=-249.44, y=4.00, z=310.44], EntitySlime['Slime'/96, l='MpServer', x=-256.97, y=4.61, z=320.07], EntityPig['Pig'/97, l='MpServer', x=-245.06, y=4.00, z=331.84], EntitySkeleton['Skeleton'/98, l='MpServer', x=-255.50, y=4.00, z=331.50], EntityPig['Pig'/99, l='MpServer', x=-245.09, y=4.00, z=338.19], EntityPig['Pig'/100, l='MpServer', x=-252.13, y=4.00, z=350.38], EntitySheep['Sheep'/103, l='MpServer', x=-231.22, y=4.00, z=249.53], EntityChicken['Chicken'/104, l='MpServer', x=-228.44, y=4.00, z=246.59], EntityChicken['Chicken'/105, l='MpServer', x=-226.59, y=4.00, z=264.59], EntityPig['Pig'/106, l='MpServer', x=-227.94, y=4.00, z=260.88], EntityZombie['Zombie'/107, l='MpServer', x=-237.25, y=4.00, z=271.38], EntityCreeper['Creeper'/108, l='MpServer', x=-230.72, y=4.00, z=262.91], EntitySkeleton['Skeleton'/109, l='MpServer', x=-235.50, y=4.00, z=252.91], EntityCreeper['Creeper'/110, l='MpServer', x=-235.88, y=4.00, z=273.47], EntitySkeleton['Skeleton'/111, l='MpServer', x=-236.72, y=4.00, z=272.50], EntityCreeper['Creeper'/112, l='MpServer', x=-228.00, y=4.00, z=273.47], EntityZombie['Zombie'/113, l='MpServer', x=-228.41, y=4.00, z=274.50], EntityHorse['Horse'/114, l='MpServer', x=-235.91, y=4.00, z=296.72], EntityItem['item.item.egg'/115, l='MpServer', x=-235.16, y=4.13, z=302.97], EntitySkeleton['Skeleton'/116, l='MpServer', x=-229.50, y=4.00, z=298.50], EntitySkeleton['Skeleton'/117, l='MpServer', x=-228.50, y=4.00, z=298.50], EntityCreeper['Creeper'/118, l='MpServer', x=-225.78, y=4.00, z=299.16], EntitySpider['Spider'/119, l='MpServer', x=-233.00, y=4.00, z=325.28], EntityZombie['Zombie'/120, l='MpServer', x=-235.03, y=4.00, z=320.44], EntityPig['Pig'/121, l='MpServer', x=-214.06, y=4.00, z=250.84], EntityPig['Pig'/122, l='MpServer', x=-216.63, y=4.00, z=258.50], EntityPig['Pig'/123, l='MpServer', x=-215.19, y=4.00, z=250.84], EntityItem['item.item.egg'/124, l='MpServer', x=-212.28, y=4.13, z=258.88], EntitySheep['Sheep'/125, l='MpServer', x=-214.66, y=4.00, z=267.19], EntitySheep['Sheep'/126, l='MpServer', x=-212.53, y=4.00, z=271.44], EntityPig['Pig'/127, l='MpServer', x=-210.84, y=4.00, z=258.88], EntitySheep['Sheep'/128, l='MpServer', x=-219.34, y=4.00, z=274.84], EntityChicken['Chicken'/129, l='MpServer', x=-214.44, y=4.00, z=292.53], EntityCreeper['Creeper'/130, l='MpServer', x=-220.22, y=4.00, z=300.88], EntityZombie['Zombie'/131, l='MpServer', x=-212.22, y=4.00, z=329.22], EntityZombie['Zombie'/132, l='MpServer', x=-217.13, y=4.00, z=372.47], EntityPig['Pig'/143, l='MpServer', x=-200.88, y=4.00, z=265.41], EntityHorse['Horse'/144, l='MpServer', x=-196.06, y=4.00, z=266.63], EntityHorse['Horse'/145, l='MpServer', x=-195.00, y=4.00, z=257.63], EntityCreeper['Creeper'/146, l='MpServer', x=-202.41, y=4.00, z=272.00], EntitySlime['Slime'/147, l='MpServer', x=-215.29, y=4.00, z=260.49], EntityPig['Pig'/148, l='MpServer', x=-206.66, y=4.00, z=263.84], EntityPig['Pig'/149, l='MpServer', x=-192.72, y=4.00, z=383.66], EntityZombie['Zombie'/150, l='MpServer', x=-198.13, y=4.00, z=375.56], EntitySlime['Slime'/151, l='MpServer', x=-205.50, y=4.35, z=391.37], EntitySheep['Sheep'/162, l='MpServer', x=-181.78, y=4.00, z=264.59], EntitySlime['Slime'/163, l='MpServer', x=-186.75, y=4.00, z=252.47], EntityPig['Pig'/164, l='MpServer', x=-178.84, y=4.00, z=274.41], EntityCreeper['Creeper'/165, l='MpServer', x=-187.06, y=4.00, z=366.00], EntitySheep['Sheep'/166, l='MpServer', x=-177.22, y=4.00, z=366.84], EntityCreeper['Creeper'/167, l='MpServer', x=-189.16, y=4.00, z=345.84], EntityZombie['Zombie'/168, l='MpServer', x=-175.56, y=4.00, z=368.91], EntityCreeper['Creeper'/169, l='MpServer', x=-177.94, y=4.00, z=374.94], EntityZombie['Zombie'/170, l='MpServer', x=-183.66, y=4.00, z=392.09], EntitySpider['Spider'/179, l='MpServer', x=-170.13, y=4.00, z=245.59], EntityZombie['Zombie'/180, l='MpServer', x=-164.41, y=4.00, z=242.59], EntityChicken['Chicken'/181, l='MpServer', x=-174.81, y=4.00, z=269.16], EntityHorse['Horse'/182, l='MpServer', x=-168.34, y=4.00, z=262.09], EntityChicken['Chicken'/183, l='MpServer', x=-168.19, y=4.00, z=271.91], EntitySheep['Sheep'/184, l='MpServer', x=-174.38, y=4.00, z=269.97], EntityChicken['Chicken'/185, l='MpServer', x=-160.63, y=4.00, z=275.44], EntityCreeper['Creeper'/186, l='MpServer', x=-163.25, y=4.00, z=287.16], EntityZombie['Zombie'/187, l='MpServer', x=-167.09, y=4.00, z=285.91], EntityZombie['Zombie'/188, l='MpServer', x=-162.34, y=4.00, z=279.88], EntityZombie['Zombie'/189, l='MpServer', x=-164.50, y=4.00, z=294.50], EntityZombie['Zombie'/190, l='MpServer', x=-170.69, y=4.00, z=291.28], EntitySlime['Slime'/191, l='MpServer', x=-159.53, y=4.00, z=286.72], EntityHorse['Horse'/192, l='MpServer', x=-164.97, y=4.00, z=355.56], EntitySpider['Spider'/193, l='MpServer', x=-162.66, y=4.00, z=350.19], EntityPig['Pig'/194, l='MpServer', x=-172.13, y=4.00, z=354.91], EntitySheep['Sheep'/195, l='MpServer', x=-160.47, y=4.00, z=366.81], EntityPig['Pig'/196, l='MpServer', x=-158.78, y=4.00, z=360.09], EntityCreeper['Creeper'/197, l='MpServer', x=-164.38, y=4.00, z=356.97], EntityZombie['Zombie'/198, l='MpServer', x=-173.50, y=4.00, z=352.50], EntityCreeper['Creeper'/199, l='MpServer', x=-178.00, y=4.00, z=354.63], EntitySheep['Sheep'/200, l='MpServer', x=-173.94, y=4.00, z=375.88], EntityHorse['Horse'/201, l='MpServer', x=-166.72, y=4.00, z=372.47], EntityClientPlayerMP['Kjasi'/349, l='MpServer', x=-195.97, y=5.62, z=312.91], EntitySpider['Spider'/202, l='MpServer', x=-160.72, y=4.00, z=389.81], EntityZombie['Zombie'/204, l='MpServer', x=-156.84, y=4.00, z=393.38], EntityZombie['Zombie'/210, l='MpServer', x=-152.06, y=4.00, z=250.41], EntitySheep['Sheep'/211, l='MpServer', x=-147.44, y=4.00, z=284.91], EntityPig['Pig'/212, l='MpServer', x=-148.66, y=4.00, z=278.22], EntityPig['Pig'/213, l='MpServer', x=-144.59, y=4.00, z=289.22], EntitySheep['Sheep'/214, l='MpServer', x=-155.28, y=4.00, z=290.84], EntitySheep['Sheep'/215, l='MpServer', x=-146.13, y=4.00, z=299.31], EntityZombie['Zombie'/216, l='MpServer', x=-148.69, y=4.00, z=294.75], EntityZombie['Zombie'/217, l='MpServer', x=-159.34, y=4.00, z=292.16], EntityPig['Pig'/218, l='MpServer', x=-155.75, y=4.00, z=289.63], EntityCreeper['Creeper'/219, l='MpServer', x=-157.00, y=4.00, z=289.50], EntitySheep['Sheep'/220, l='MpServer', x=-146.16, y=4.00, z=323.81], EntitySheep['Sheep'/221, l='MpServer', x=-150.38, y=4.00, z=328.84], EntityHorse['Horse'/222, l='MpServer', x=-152.50, y=4.00, z=360.47], EntityItem['item.item.egg'/223, l='MpServer', x=-146.09, y=4.13, z=363.41], EntityHorse['Horse'/224, l='MpServer', x=-148.53, y=4.00, z=352.63], EntityPig['Pig'/225, l='MpServer', x=-160.06, y=4.00, z=349.94], EntityPig['Pig'/226, l='MpServer', x=-150.19, y=4.00, z=362.38], EntityChicken['Chicken'/227, l='MpServer', x=-146.59, y=4.00, z=374.03], EntityHorse['Horse'/228, l='MpServer', x=-145.56, y=4.00, z=378.09], EntityChicken['Chicken'/229, l='MpServer', x=-148.41, y=4.00, z=383.63], EntityCreeper['Creeper'/241, l='MpServer', x=-135.72, y=4.00, z=238.91], EntityZombie['Zombie'/243, l='MpServer', x=-139.50, y=4.00, z=247.50], EntityCow['Cow'/244, l='MpServer', x=-129.75, y=4.00, z=247.22], EntityChicken['Chicken'/245, l='MpServer', x=-132.47, y=4.00, z=262.53], EntityPig['Pig'/246, l='MpServer', x=-143.25, y=4.00, z=293.19], EntityPig['Pig'/247, l='MpServer', x=-135.81, y=4.00, z=349.47], EntityPig['Pig'/248, l='MpServer', x=-136.84, y=4.00, z=358.16], EntityChicken['Chicken'/249, l='MpServer', x=-140.78, y=4.00, z=363.16], EntityCow['Cow'/251, l='MpServer', x=-131.09, y=4.00, z=375.06], EntityChicken['Chicken'/253, l='MpServer', x=-141.09, y=4.00, z=384.19], EntityCow['Cow'/255, l='MpServer', x=-132.72, y=4.00, z=387.78]]
    	Retry entities: 0 total; []
    	Server brand: fml,forge
    	Server type: Integrated singleplayer server
    Stacktrace:
    	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Windows 7 (amd64) version 6.1
    	Java Version: 1.8.0_31, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 438450064 bytes (418 MB) / 847847424 bytes (808 MB) up to 1060372480 bytes (1011 MB)
    	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 55 mods loaded, 55 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
    	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCHIJAAAA	ImmibisMicroblocks{59.1.1} [Immibis's Microblocks] (immibis-microblocks-59.1.1.jar) 
    	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
    	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    	UCHIJAAAA	BuildCraft|Core{7.1.11} [BuildCraft] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	BuildCraft|Transport{7.1.11} [BC Transport] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	BuildCraft|Silicon{7.1.11} [BC Silicon] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	BuildCraft|Factory{7.1.11} [BC Factory] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	IC2{2.2.789-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.789-experimental.jar) 
    	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    	UCHIJAAAA	LogisticsPipes{0.9.3.61} [Logistics Pipes] (logisticspipes-0.9.3.61.jar) 
    	UCHIJAAAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.0.jar) 
    	UCHIJAAAA	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
    	UCHIJAAAA	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) 
    	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
    	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar) 
    	UCHIJAAAA	BuildCraft|Builders{7.1.11} [BC Builders] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	BuildCraft|Energy{7.1.11} [BC Energy] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	BuildCraft|Robotics{7.1.11} [BC Robotics] (buildcraft-7.1.11.jar) 
    	UCHIJAAAA	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    	UCHIJAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
    	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
    	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    	UCHIJAAAA	nhlib{1.0.0} [NHAVE's Library] (nhlib-1.7.10-1.0.0.jar) 
    	UCHIJAAAA	nhwrench{2.2.3} [NHAVE's OmniWrench 2] (nhwrench2-1.7.10-2.2.3.jar) 
    	UCHIJAAAA	numina{0.4.0.119} [Numina] (Numina-0.4.0.119.jar) 
    	UCHIJAAAA	PowerConverters{1.7.10_3.3.0-jenkins.76} [Power Converters] (PowerConverters-1.7.10_3.3.0-jenkins.76.jar) 
    	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GTX 760/PCIe/SSE2'
    	CoFHCore: -[1.7.10]3.0.3-303
    	ThermalFoundation: -[1.7.10]1.2.0-102
    	ThermalExpansion: -[1.7.10]4.0.3B1-218
    	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    	MineFactoryReloaded: -[1.7.10]2.8.0-104
    	NetherOres: -[1.7.10]2.3.0-12
    	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    	LWJGL: 2.9.1
    	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
    	GL Caps: Using GL 1.3 multitexturing.
    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
    Anisotropic filtering is supported and maximum anisotropy is 16.
    Shaders are available because OpenGL 2.1 is supported.
    
    	Is Modded: Definitely; Client brand changed to 'fml,forge'
    	Type: Client (map_client.txt)
    	Resource Packs: [KJ_Realism_1.8.x]
    	Current Language: English (US)
    	Profiler Position: N/A (disabled)
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	Anisotropic Filtering: On (4)

**Comment by Kjasi** [comment]
Fixed by updating IC2 to #790.
