### ISSUE TITLE
Crashes with Galacticraft and Tinkers' Construct

### ISSUE THREAD

**Issue by C1ffisme** [Chicken-Bones/NotEnoughItems#314]
Here is the report, sorry for the long message:

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 12/25/15 12:54 PM
Description: Ticking screen

java.lang.ArithmeticException: / by zero
	at micdoodle8.mods.galacticraft.core.nei.IngotCompressorRecipeHandler$CompressorRecipe.getOtherStack(IngotCompressorRecipeHandler.java:235)
	at micdoodle8.mods.galacticraft.core.nei.IngotCompressorRecipeHandler$CompressorRecipe.getOtherStacks(IngotCompressorRecipeHandler.java:224)
	at codechicken.nei.recipe.TemplateRecipeHandler.getOtherStacks(TemplateRecipeHandler.java:501)
	at codechicken.nei.recipe.GuiRecipe.refreshSlots(GuiRecipe.java:228)
	at codechicken.nei.recipe.GuiRecipe.refreshPage(GuiRecipe.java:201)
	at codechicken.nei.recipe.GuiRecipe.func_73876_c(GuiRecipe.java:134)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.nei.IngotCompressorRecipeHandler$CompressorRecipe.getOtherStack(IngotCompressorRecipeHandler.java:235)
	at micdoodle8.mods.galacticraft.core.nei.IngotCompressorRecipeHandler$CompressorRecipe.getOtherStacks(IngotCompressorRecipeHandler.java:224)
	at codechicken.nei.recipe.TemplateRecipeHandler.getOtherStacks(TemplateRecipeHandler.java:501)
	at codechicken.nei.recipe.GuiRecipe.refreshSlots(GuiRecipe.java:228)
	at codechicken.nei.recipe.GuiRecipe.refreshPage(GuiRecipe.java:201)
	at codechicken.nei.recipe.GuiRecipe.func_73876_c(GuiRecipe.java:134)

-- Affected screen --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['C1ff'/288, l='MpServer', x=180.54, y=106.62, z=187.89]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (20,64,196), Chunk: (at 4,4,4 in 1,12; contains blocks 16,0,192 to 31,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 232426 game time, 232426 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntitySheep['Sheep'/275, l='MpServer', x=215.88, y=80.00, z=152.81], EntitySheep['Sheep'/274, l='MpServer', x=219.97, y=77.00, z=145.03], EntitySheep['Sheep'/273, l='MpServer', x=213.78, y=79.00, z=146.78], EntityZombie['Zombie'/2861, l='MpServer', x=254.50, y=98.00, z=236.50], EntitySkeleton['Skeleton'/2862, l='MpServer', x=163.53, y=12.00, z=256.09], EntityBat['Bat'/280, l='MpServer', x=221.75, y=33.10, z=217.13], EntityZombie['Zombie'/2977, l='MpServer', x=178.44, y=91.00, z=121.13], EntityCreeper['Creeper'/2869, l='MpServer', x=119.50, y=82.00, z=157.50], EntitySkeleton['Skeleton'/3006, l='MpServer', x=142.50, y=79.00, z=174.50], EntityCreeper['Creeper'/2870, l='MpServer', x=119.50, y=82.00, z=155.50], EntitySkeleton['Skeleton'/2822, l='MpServer', x=226.50, y=33.00, z=218.91], EntitySpider['Spider'/2823, l='MpServer', x=226.50, y=33.00, z=217.03], EntityCreeper['Creeper'/2000, l='MpServer', x=130.50, y=77.00, z=172.50], EntitySheep['Sheep'/174, l='MpServer', x=112.88, y=77.00, z=118.25], EntityCreeper['Creeper'/2588, l='MpServer', x=129.50, y=31.00, z=113.50], EntityCreeper['Creeper'/2011, l='MpServer', x=122.50, y=21.00, z=236.50], EntitySpider['Spider'/2590, l='MpServer', x=120.13, y=31.01, z=113.19], GCEntityClientPlayerMP['C1ff'/288, l='MpServer', x=180.54, y=106.62, z=187.89], EntitySheep['Sheep'/295, l='MpServer', x=235.03, y=80.00, z=164.06], EntitySheep['Sheep'/296, l='MpServer', x=234.03, y=80.00, z=167.09], EntitySkeleton['Skeleton'/176, l='MpServer', x=113.50, y=30.00, z=144.50], EntitySheep['Sheep'/298, l='MpServer', x=238.22, y=79.00, z=154.44], EntitySheep['Sheep'/177, l='MpServer', x=120.53, y=76.00, z=213.69], EntitySheep['Sheep'/299, l='MpServer', x=234.75, y=76.00, z=143.88], EntitySheep['Sheep'/182, l='MpServer', x=123.50, y=76.00, z=226.63], EntitySkeleton['Skeleton'/2842, l='MpServer', x=184.69, y=91.00, z=130.69], EntitySheep['Sheep'/183, l='MpServer', x=118.34, y=81.00, z=226.50], EntitySkeleton['Skeleton'/2841, l='MpServer', x=184.31, y=91.00, z=129.69], EntitySheep['Sheep'/201, l='MpServer', x=140.09, y=73.00, z=217.13], EntitySheep['Sheep'/203, l='MpServer', x=143.22, y=80.00, z=215.19], EntitySheep['Sheep'/202, l='MpServer', x=141.50, y=78.00, z=217.34], EntitySheep['Sheep'/197, l='MpServer', x=139.53, y=76.00, z=186.78], EntitySheep['Sheep'/196, l='MpServer', x=141.06, y=76.00, z=181.25], EntitySheep['Sheep'/199, l='MpServer', x=136.47, y=77.00, z=197.78], EntityBat['Bat'/2926, l='MpServer', x=128.44, y=32.97, z=110.59], EntitySheep['Sheep'/195, l='MpServer', x=129.06, y=77.00, z=169.56], EntitySheep['Sheep'/194, l='MpServer', x=135.13, y=77.00, z=175.84], EntitySheep['Sheep'/212, l='MpServer', x=153.44, y=79.00, z=216.34], EntitySheep['Sheep'/213, l='MpServer', x=146.91, y=71.00, z=233.16], EntityBat['Bat'/2395, l='MpServer', x=241.38, y=43.73, z=216.25], EntitySkeleton['Skeleton'/1180, l='MpServer', x=242.50, y=84.00, z=193.50], EntitySheep['Sheep'/209, l='MpServer', x=155.63, y=80.00, z=169.47], EntitySheep['Sheep'/210, l='MpServer', x=139.78, y=80.00, z=180.50], EntitySheep['Sheep'/229, l='MpServer', x=162.50, y=82.00, z=197.50], EntitySheep['Sheep'/228, l='MpServer', x=162.50, y=82.00, z=197.50], EntitySheep['Sheep'/227, l='MpServer', x=160.72, y=105.00, z=156.88], EntitySheep['Sheep'/252, l='MpServer', x=186.31, y=100.00, z=148.47], EntitySheep['Sheep'/253, l='MpServer', x=187.53, y=104.00, z=148.47], EntityZombie['Zombie'/963, l='MpServer', x=133.50, y=84.00, z=162.50], EntityBat['Bat'/2549, l='MpServer', x=122.28, y=20.10, z=199.25], EntityBat['Bat'/2550, l='MpServer', x=131.44, y=19.17, z=199.84], EntityBat['Bat'/2546, l='MpServer', x=122.28, y=19.00, z=198.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (i386) version 3.16.0-55-generic
	Java Version: 1.7.0_91, Oracle Corporation
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 155813200 bytes (148 MB) / 449441792 bytes (428 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.406.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.406.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 10.1.3' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2 GL version 3.0 Mesa 10.1.3, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [nopumpkinblur]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
I tried to find the usages of an iron ingot, however this seems to not work after going through crafting and unshaped crafting. It appears that it cannot show Galacticraft's "Compressor" recipes.

I'm not sure if this is an issue with NEI or not.

**Comment by C1ffisme** [comment]
This is also a problem when looking for recipes for a seared ingot, from Tinkers' Construct.
