### ISSUE TITLE
Exit Code -1

### ISSUE THREAD

**Issue by Straighten-Your-Back** [Chicken-Bones/NotEnoughItems#394]
Having experimented thoroughly, I'm certain this issue is Not Enough Items. Happens if Not Enough Items is installed and nothing else (except its necessary depencies) are; happens regardless of what else is installed.

Minecraft goes through the full (or at least most of the) launch sequence, then exits "with code -1".

**Comment by ChrisJStone** [comment]
What version of Minecraft are you using? What is the contents of your error log?

**Comment by ardilaaa** [comment]
How did you solve it? I'm using 1.7.10 same problem I have  me. please somebody help

**Comment by ChrisJStone** [comment]
@ardilaaa without the crash log from minecraft there's not much I can suggest other then using the latest version of forge which is 10.13.4.1614 for 1.7.10 also make sure you have codechickencore and codechickenlib in your mods folder.

**Comment by solundev** [comment]
**CLOSE IT** issue can be fixed by having both core and lib at mods folder.
.minecraft/mods/1.7.10/[place core and lib here]
.minecraft/mods[place mods here]

**Comment by solundev** [comment]
> 

also, this error does not generate crash logs

**Comment by ChrisJStone** [comment]
incorrect the error can be reproduced with just cccore and cclib. Here is the log.

[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.NoClassDefFoundError: codechicken/lib/asm/CC_ClassWriter
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.asm.MCPDeobfuscationTransformer$LoadPlugin.injectData(MCPDeobfuscationTransformer.java:57)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.CC_ClassWriter
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 12 more
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.NullPointerException
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[16:48:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 14 more
[16:48:47] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
